Added an Error Handler
UncaughtException: This will will help catch all error that we failed to catch-we might have thrown it up the stack somewhere but forgot to catch it
Unhandledexceptions: This is help check if there is any error we failed to handle in the application
Gloabal Error handler: This is a customer Error which extends the default Error class, you have to pass in the statusCode and the message you want to display - this way we will better understand what each error is and where it it from
The global error handler delivers two types of errors: In DEVELOPMENT: it will show the entire Error object including the stack whereas in production the stack is not included.